import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "components/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>RCF eTest Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.courses}>
          <div>
            <h1>Select Course of your choice.</h1>
          </div>
          <div className={styles.grid}>
            <div className={styles.course}>
              <img src="/math.png" />
              <div className={styles.courseTitle}>
                <h3>Math111</h3>
                <span>partial fractions, binomal expa...</span>
              </div>
            </div>
            <div className={styles.course}>
              <img src="/math.png" />
              <div className={styles.courseTitle}>
                <h3>Math111</h3>
                <span>partial fractions, binomal expa...</span>
              </div>
            </div>
            <div className={styles.course}>
              <img src="/math.png" />
              <div className={styles.courseTitle}>
                <h3>Math111</h3>
                <span>partial fractions, binomal expa...</span>
              </div>
            </div>
            <div className={styles.course}>
              <img src="/math.png" />
              <div className={styles.courseTitle}>
                <h3>Math111</h3>
                <span>partial fractions, binomal expa...</span>
              </div>
            </div>
            <div className={styles.course}>
              <img src="/math.png" />
              <div className={styles.courseTitle}>
                <h3>Math111</h3>
                <span>partial fractions, binomal expa...</span>
              </div>
            </div>
          </div>
          <div>
            <button className={styles.buttonTwo}>START QUIZ</button>
          </div>
        </div>
      </main>
    </>
  );
}
