import Head from "next/head";
import Image from "next/image";
import Quiz from "../../components/examDisp";
import { Inter } from "next/font/google";
import styles from "components/styles/Home.module.css";
import { quizData } from "../../constants/mat111";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  console.log("this is", quizData);
  return (
    <>
      <Head>
        <title>RCF eTest Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
          <img src="/rcficon.png" />
          <span>000000</span>
        </div>
        <div className={styles.exambody}>
          <Quiz quizData={quizData} />
        </div>
      </main>
    </>
  );
}
