import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from 'components/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>RCF eTest Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.loginCard}>
          <img className={styles.loginCardImg} src="/rcficon.png"/>
          {/* <Image className={styles.loginCardImg} src="/rcflogo.png" /> */}
          <div>
            <input className={styles.inputField} type='text' placeholder='User ID' />     
          </div>
          <div>
          <input className={styles.inputField} type='text' placeholder='OTP'></input>
          </div>
          <button className={styles.buttonOne}>LOGIN</button>
        </div>
      </main>
    </>
  )
}
